### ISSUE TITLE
Bug: command 'short-commands.activatePalette' not found

### ISSUE THREAD

**Issue by callamaris** [laginha87/vscode-short-commands#19]
the extension does not work for me.

when i try the command i get the error message : command 'short-commands.activatePalette' not found

Windows 10
Version: 1.27.1 (system setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Datum: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64

**Comment by callamaris** [comment]
Hi, i am using version 0.0.4 (current version in marketplace)

**Comment by callamaris** [comment]
Seems like the issue is related to localization.

In commands.ts, line 20 the variable __title__ is an object, not a string, when localization is enabled.

`this.description = category ? `${category}: ${title}` : title;`

When __category__ is != undefined the title is implicitly converted to a string, wich can be splitted in the next line.

```
    this.short = this.description
      .split(" ")
```

But with an object, the function split throws an exception.

The object has 2 properties, __original__ (english text) and __value__ (localized text).

Not sure, if its better to use the localized or the original text for the shortcuts. The original text would be more consistent across different systems, but localized shortcuts might be more intuitive.

Maybe its a good idea to to add a config parameter for that, with localized shortcuts as default?

**Comment by laginha87** [comment]
Wow, wasn't expecting that. I thought it was some issue with it being in windows as I haven't tested the extension there, was going to set up a VM to look into it.
Thanks for looking into it, I'll fix it when I can to use the value to generate the command. I will add a config for it later. You're

**Comment by balazser** [comment]
Hi, I've just installed the extension. Really like the idea but still get this error ```command 'short-commands.activatePalette' not found```. Any news regarding this?

**Comment by laginha87** [comment]
Hi @balazser thanks for installing the extension, will look into the issue when I can, it should be unrelated to the initial issue.

**Comment by balazser** [comment]
Thank you @laginha87,
Can I help somehow?
My spec:
OSX 10.14.4 (18E226)
VS CODE Version 1.34.0 (1.34.0)

**Comment by laginha87** [comment]
hey @balazser sorry to take so long to fix this. Launched a new version it should fix the issue.
